# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-11-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0221_ensure_schema_and_reports'),
        ('addons_microsoftteams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='has_grdm_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('email_address', 'node_settings', 'external_account')]),
        ),
    ]
