# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-08-05 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_microsoftteams', '0002_microsoftteams_external_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftteams',
            name='app_name',
            field=models.CharField(default='Microsoft Teams', max_length=128),
        ),
    ]
