# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-11-01 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_microsoftteams', '0003_auto_20221028_0207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('email_address', 'node_settings', 'external_account')]),
        ),
    ]
