# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-11-11 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_microsoftteams', '0004_auto_20221101_2355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('email_address', 'node_settings', 'external_account', 'is_active')]),
        ),
    ]
