# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-08-29 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_microsoftteams', '0005_auto_20220828_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('email_address', 'node_settings')]),
        ),
    ]
