# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-06 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_microsoftteams', '0006_auto_20220829_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicrosoftTeams',
            new_name='Meetings',
        ),
    ]
