# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-10-27 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_webexmeetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('email_address', 'node_settings', 'external_account', 'is_guest')]),
        ),
    ]
