# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-06 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0221_ensure_schema_and_reports'),
        ('addons_webexmeetings', '0006_auto_20220829_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('organizer_fullname', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('join_url', models.TextField(max_length=512)),
                ('meetingid', models.TextField(max_length=512)),
                ('meeting_password', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('app_name', models.CharField(default='Webex Meetings', max_length=128)),
                ('attendees', models.ManyToManyField(related_name='attendees_meetings', to='addons_webexmeetings.Attendees')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='MeetingsAttendeesRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('webex_meetings_invitee_id', models.TextField(blank=True, max_length=512, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_webexmeetings.Attendees')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_webexmeetings.Meetings')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.RemoveField(
            model_name='webexmeetings',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='webexmeetings',
            name='attendees_specific',
        ),
        migrations.RemoveField(
            model_name='webexmeetings',
            name='external_account',
        ),
        migrations.RemoveField(
            model_name='webexmeetings',
            name='node_settings',
        ),
        migrations.RemoveField(
            model_name='webexmeetingsattendeesrelation',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='webexmeetingsattendeesrelation',
            name='webex_meetings',
        ),
        migrations.DeleteModel(
            name='WebexMeetings',
        ),
        migrations.DeleteModel(
            name='WebexMeetingsAttendeesRelation',
        ),
        migrations.AddField(
            model_name='meetings',
            name='attendees_specific',
            field=models.ManyToManyField(related_name='attendees_specific_meetings', through='addons_webexmeetings.MeetingsAttendeesRelation', to='addons_webexmeetings.Attendees'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='external_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webexmeetings_meetings', to='osf.ExternalAccount'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='node_settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_webexmeetings.NodeSettings'),
        ),
    ]
