# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0221_ensure_schema_and_reports'),
        ('addons_webexmeetings', '0007_auto_20220906_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsattendeesrelation',
            name='external_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webexmeetings_meetings_attendees_relation', to='osf.ExternalAccount'),
        ),
    ]
