# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-07-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0221_ensure_schema_and_reports'),
        ('addons_zoommeetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeetings',
            name='external_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.ExternalAccount'),
        ),
    ]
