# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-06 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_zoommeetings', '0003_zoommeetings_app_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoomMeetings',
            new_name='Meetings',
        ),
    ]
