# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-13 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0084_merge_20180702_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='update_date',
            new_name='upload_file_modified_at',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='update_user',
            new_name='upload_file_modified_user',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='validation_date',
            new_name='verify_date',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='validation_user',
            new_name='verify_user',
        ),
        migrations.RemoveField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='create_user',
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='upload_file_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='upload_file_created_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='upload_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
