# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdmFileTimestamptokenVerifyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('key_file_name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=24)),
                ('project_id', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=25, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('timestamp_token', models.BinaryField(blank=True, null=True)),
                ('inspection_result_status', models.IntegerField(default=0)),
                ('upload_file_created_user', models.IntegerField(blank=True, null=True)),
                ('upload_file_created_at', models.DateTimeField(blank=True, null=True)),
                ('upload_file_modified_user', models.IntegerField(blank=True, null=True)),
                ('upload_file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('upload_file_size', models.IntegerField(blank=True, null=True)),
                ('verify_user', models.IntegerField(blank=True, null=True)),
                ('verify_date', models.DateTimeField(blank=True, null=True)),
                ('verify_file_created_at', models.DateTimeField(blank=True, null=True)),
                ('verify_file_modified_at', models.DateTimeField(blank=True, null=True)),
                ('verify_file_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmUserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('guid', models.IntegerField()),
                ('key_name', models.CharField(max_length=50)),
                ('key_kind', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('delete_flag', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
