# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_quota', models.IntegerField(default=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
