# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-21 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_auto_20190308_0043'),
        ('osf', '0135_widgetposition'),
    ]

    operations = [
    ]
