# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-08 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0145_auto_20190710_0451'),
        ('osf', '0140_mapcore_20190520_0122'),
    ]

    operations = [
    ]
