# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-23 07:58
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0177_auto_20201007_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='webhook_url',
            field=osf.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
