# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-14 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0178_externalaccount_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdmWebMeetingApps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RdmWorkflows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_description', models.CharField(max_length=256, unique=True)),
                ('workflow_apps', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
