# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-10 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0211_auto_20200709_1320'),
        ('osf', '0176_auto_20200717_1339'),
    ]

    operations = [
    ]
