# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-25 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesettings',
            name='folder_id',
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='folder_name',
        ),
    ]
