# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='zoom_meetings_mail',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('user_guid', 'node_settings'), ('microsoft_teams_mail', 'node_settings'), ('zoom_meetings_mail', 'node_settings'), ('webex_meetings_mail', 'node_settings')]),
        ),
    ]
