# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-25 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0002_auto_20201225_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='folder_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='folder_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
