# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-14 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0179_rdmwebmeetingapps_rdmworkflows'),
        ('addons_integromat', '0003_auto_20201225_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMeetingInformation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('organizer', models.CharField(max_length=128)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('join_url', models.CharField(max_length=128)),
                ('meetingid', models.CharField(max_length=128)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.RdmWebMeetingApps')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_guid', models.CharField(max_length=128)),
                ('microsoft_teams_user_object', models.CharField(max_length=128)),
                ('microsoft_teams_mail', models.CharField(max_length=128)),
                ('node_settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.RdmWorkflows')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=128)),
                ('node_settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryWorkflowMap',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.Categories')),
                ('node_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings', to_field=b'_id')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.RdmWorkflows')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, to='addons_integromat.Attendees'),
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='node_settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings'),
        ),
    ]
