# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0004_auto_20210114_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmeetinginformation',
            name='join_url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='allmeetinginformation',
            name='meetingid',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='microsoft_teams_mail',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='microsoft_teams_user_object',
            field=models.CharField(max_length=256),
        ),
    ]
