# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0006_workflowexecutionmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionmessages',
            name='create_microsoft_teams_meeting',
        ),
        migrations.RemoveField(
            model_name='workflowexecutionmessages',
            name='delete_microsoft_teams_meeting',
        ),
        migrations.RemoveField(
            model_name='workflowexecutionmessages',
            name='update_microsoft_teams_meeting',
        ),
        migrations.AddField(
            model_name='workflowexecutionmessages',
            name='integromat_msg',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionmessages',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowexecutionmessages',
            name='timestamp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
