# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-25 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0007_auto_20210222_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='node_settings',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='node_settings',
        ),
        migrations.RemoveField(
            model_name='categoryworkflowmap',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryworkflowmap',
            name='node_settings',
        ),
        migrations.RemoveField(
            model_name='categoryworkflowmap',
            name='workflow',
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='folder_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CategoryWorkflowMap',
        ),
    ]
