# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-28 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0015_auto_20240227_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiimporttask',
            name='task_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
